# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 98b1979b4bc5bce17ca6d859191fdc79bc6be4c5c04255ea9f1e5327a30e29aeb05ef2605c6115020daa0d58fc311c88be9ab9e31e024565e3583064763de45b

test:
  secret_key_base: c9b143c18315f18f43a317808f9a76a3d8d8068f386666024735a135e5d3737432a2e034c2738933eb57dbcfbf79f02334c828c45fc490583c0f7e603dbe95e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
